default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Root@123

development:
  <<: *default
  database: learning_grape_api_development

test:
  <<: *default
  database: learning_grape_api_test

production:
  <<: *default
  database: learning_grape_api_production
  username: learning_grape_api
  password: <%= ENV["LEARNING_GRAPE_API_DATABASE_PASSWORD"] %>
